const TEAMS = [
  { name: 'KK Alkar', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Cibona', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Depolink Škrljevo', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Dinamo Zagreb', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Dubrava', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Dubrovnik', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Kvarner', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Samobor', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Split', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Virtus Zagreb', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Zabok', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },
  { name: 'KK Zadar', competitions: ['SuperSport Premijer liga', 'KUP «K. ĆOSIĆ»'] },

  { name: 'ŽKK Brod na Savi', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'ŽKK FSV Rijeka', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'KA Žana Lelas Split', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'ŽKK Medveščak', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'ŽKK Plamen Požega', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'ŽKK Ragusa', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'ŽKK Studio Zagreb', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'ŽKK Šibenik', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'ŽKK Trešnjevka 2009', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'ŽKK Zadar', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },
  { name: 'ŽKK Zadar Plus', competitions: ['PREMIJER ŽENSKA LIGA', 'KUP «R. MEGLAJ-RIMAC»'] },

  { name: 'KK Aleta Puntamika', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Crikvenica', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Đakovo', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Gorica', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Hermes Analitica', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Jazine Arbanasi', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Marsonia', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'HAKK Mladost', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Novi Zagreb', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Omiš-Čagalj Tours', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Radnik Križevci', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Ribola Kaštela', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'GKK Šibenka', competitions: ['PRVA MUŠKA LIGA'] },
  { name: 'KK Zagreb', competitions: ['PRVA MUŠKA LIGA'] }
];

const VENUES = [
  'Košarkaški centar Dražen Petrović',
  'SŠD Boško Božić Pepsi (Trnsko)',
  'Športska dvorana Dubrava',
  'ŠŠD Peščenica',
  'SD Sutinska Vrela',
  'Dom košarke Cedevita',
  'Dvorana Krešimira Ćosića (ŠC Višnjik)',
  'Dvorana Jazine',
  'Košarkaška dvorana Split (Gripe)',
  'SC Gripe – mala dvorana',
  'Gradska športska dvorana Ivica Glavan – Ićo (Sinj)',
  'Gradska sportska dvorana Zabok',
  'Sportska dvorana Samobor',
  'Sportski centar Zamet (Rijeka)',
  'SRC 3. maj (Rijeka)',
  'Sportska dvorana Kostrena',
  'ŠD Gospino polje (Dubrovnik)',
  'SD Baldekin (Šibenik)',
  'Sportska dvorana Vijuš (Slavonski Brod)',
  'Sportska dvorana Tomislav Pirc (Požega)',
  'Sportska dvorana Velika Gorica',
  'Sportska dvorana Crikvenica',
  'Sportska dvorana Đakovo',
  'Sportska dvorana Omiš',
  'Sportska dvorana Kaštela',
  'Sportska dvorana Križevci'
];

module.exports = { TEAMS, VENUES };
